.gitignore
.merlin
Make.cfg
Makefile
src.8.10/abstraction.mlg
src.8.10/debug.ml
src.8.10/declare_translation.ml
src.8.10/dune

- port to new mlg preprocessor format [straightforward]
- fix w.r.t master; I will include paramcoq in Coq's CI after this is merged,
- add Dune file. A very convenient developer setup is now:
```
$ cd $coq_location
$ ln -s paramcoq/src.8.10
$ make -f Makefile.dune voboot
$ dune build @check # have fun!
```

[coq] Coq Updates:

---

src/declare_translation.ml
src/parametricity.ml

I am afraid this option cannot be implemented after
https://github.com/coq/coq/pull/9410. It seems unused anyway.

Remove option `Parametricity Program`.

---

.travis.yml
default.nix
meta.yml

I noticed that paramcoq CI tests are failing on v8.10 because the opam image for this branch does not exist yet: https://travis-ci.com/coq-community/paramcoq/builds/107312718
What I propose with this PR is to circumvent the problem by using coq-community's other vetted solution for CI testing, that relies on Nix. The point here is that it works as long as there is a v8.10 branch in the Coq repository, and still reuses cached binary builds of Coq.
The `.travis.yml` and `default.nix` files were generated automatically from the templates in https://github.com/coq-community/manifesto/tree/master/templates from a `meta.yml` file reduced to the bare minimum. The `.travis.yml` file is quite big because it also contains the infrastructure for building with opam even if it's not used in this case.

Nix testing for v8.10

---

src/declare_translation.ml

The change is that flag `Global` becomes `Global ImportDefaultBehavior` so as to distinguish it from the kind of globality which does not import the qualified names. See coq/coq#8726.
Note: To be merged synchronously with coq/coq#8726.

Adapting to PR #8726 (more structured "locality" type).

---

test-suite/Makefile

This is a variant of #40 following Théo’s suggestion.

Examples: disable template polymorphism check

---

src/debug.ml

PR coq/coq#13143 proposes to clarify that the integer argument of `Pp.h` boxes is irrelevant. There was three uses of `Pp.h` in paramcoq.
The h-boxes were called here with a very high integer. It might have been by irony knowing that the argument is dummy or to move the printing very far in the margin because it is intended to be debug printing to put far in the margin. The values were 100 and 140, so I assumed it was intended and I replaced the h-box by an hov-box.
To be merged synchronously with coq/coq#13143.

Adapt to Coq PR#13143: Pp.h does not take a (dummy) integer anymore.

---

test-suite/Makefile

It consumes too much memory breaking CI (eg https://gitlab.com/coq/coq/-/jobs/1144081161)

Disable native compile in test suite

---

src/debug.ml

This leads to a slight simplication of the code.
This has to be merged synchrounously with coq/coq#14692. Thanks in advance.

Adapting to Coq PR #14692: UContext now includes the names by default

---

src/parametricity.ml

Hi,
PR coq/coq#14726 made a uniformization of names in `Context.Rel` and `Context.Named` choosing the name `instance` to replace `rel_context_vect`.
PR coq/coq#14746 is going to add a variant of `Vars.subst_instance_context` in `EConstr.Vars.subst_instance_context`, thus requiring a desambiguation.
This paramcoq PR adapts to these changes. The first one is compatible with any version of Coq master after the (recent) merge of coq/coq#14726. The second one is compatible with current Coq master. So, this is compatible with current Coq master in bot cases and can be merged as soon as now. Thanks in advance.

Adapt to Coq PR #14726 and #14746: rel_context_vect renamed into instance and subst_instance_context also in econstr

---

.github/workflows/coq-action.yml
coq-paramcoq.opam

The current CI configuration could prove a handful to maintain, so here I use opam testing facilities, already used by projects such as Equations, to simplify it.

use opam testing facilities to run tests in CI

---

.gitignore
Makefile
_CoqProject
dune-project
src/dune
theories/Param.v
theories/dune

As highlighted by #56, there is no pure Coq interface to this plugin. This means that a user has to know and perform the declaration:
```coq
Declare ML Module "paramcoq".
```
This is not likely to be figured out except by advanced users. In this PR, I introduce a Coq interface, so that users can write
```coq
From Param Require Import Param.
```
to get access to plugin commands. This has the side-effect of making the `coqdep` warning from #56 go away.
For easier development, I also introduce a `_CoqProject` file, fix the Dune-based build, and use a coq-community standard makefile. As far as I can tell, all functionality is completely untouched.
If this PR is accepted, I will do a separate PR with improved documentation.

introduce Params.v file

---

.github/workflows/docker-action.yml
.gitignore
README.md
coq-paramcoq.opam
meta.yml

Document how to cleanly load the plugin and explain its commands in a more structured way using GitHub markdown facilities. Use more standard placement of files and generate some boilerplate.

Refine documentation

---

src/parametricity.ml

The adaptation is simple. To be merged synchronously with coq/coq#14711 though. Thanks in advance.

Adapting to Coq PR #14711: Evd.univ_entry returns also the universe binders

---

src/parametricity.ml

We insert a translation function which emulates the previous behavior. Note also that `subst_instance_constr` now needs a disambiguation.
This is to be merged synchronously with coq/coq#14846.
Note: In passing, and independently, we adapt to a warning (`lift_rel_context` now provided by Coq).

Adapt to Coq PR #14846: references to inductive types in the type of constructors are directly Ind rather than Rel nodes

---

.github/workflows/docker-action.yml
src/abstraction.mlg

After some stronger invariant upstream, the name here has to match the
name used in `Declare ML Module`.

[coq] Use findlib name in DECLARE PLUGIN

---

src/declare_translation.ml

This is necessary for https://github.com/coq/coq/pull/16578, but should be backward compatible.

Use `Declaremods.start_module` instead of low-level Lib API

---

src/declare_translation.ml
src/parametricity.ml

This PR addresses some warnings while compiling paramcoq with recent Coq (such as 8.18):
- use of `mkConstU` so as to deal with universes
- some renamings from coq/coq#15582

Use of mkConstU and use of the new names of decompose_lam & cie (#15582)

---

test-suite/ListQueue.v
test-suite/Makefile
test-suite/bug3.v
test-suite/bug5.v
test-suite/example.v

This PR addresses two stdlib renamings while compiling paramcoq's examples with recent Coq (such as 8.18): `app_assoc` and `Nat.divmod`.
It also fixes a mispelling which was supposingly unintended (revealed by a new Coq warning).

Adapt to Coq stdlib renamings and fixes a mispelled constructor

---

src/parametricity.ml

This PR ensures that arguments of parametricity predicates/relations have a "nice" name. E.g., before:
```
Parametricity nat.
Print nat_R.
(*
Inductive nat_R : nat -> nat -> Set :=
nat_R_O_R : nat_R 0 0
| nat_R_S_R : forall H H0 : nat, nat_R H H0 -> nat_R (S H) (S H0).
*)
```
with the PR:
```
Parametricity nat.
Print nat_R.
(*
Inductive nat_R : nat -> nat -> Set :=
nat_R_O_R : nat_R 0 0
| nat_R_S_R : forall n₁ n₂ : nat, nat_R n₁ n₂ -> nat_R (S n₁) (S n₂).
*)
```

Give a name derived from the name of the type to dependent variables

---

src/parametricity.ml

We freshen on sight the levels that are known to be template.
This should be backwards compatible.

Work around the non-linearity of template parameter levels.

---

src/declare_translation.ml

Should be backwards compatible.

Adapt w.r.t. coq/coq#20060.

---

src/parametricity.ml

Adapt w.r.t. coq/coq#20278.

---

src/parametricity.ml

Changed bound_names definition in rocq

adapt to rocq-prover/rocq#20496 (changed bound_names)
